##
# update instances, install ntp, install clam av and jumpcloud key
##
- name: update instances, install ntp, install clam av and jumpcloud key.
  hosts: all
  tags: ['pre-deploy']
  gather_facts: no
  become: yes
  tasks:
    - name: update
      command: ["/bin/sh","-c"]
      args: [sudo apt update -y;
             sudo apt-get install ntp;
             sudo apt-get ntp-update;
             sudo apt-get install clamav]
      tags: ['ubuntu']
      
    

