- name: Setup ansible
  hosts: all
  tags: ['pre-deploy']
  gather_facts: no
  become: yes
  tasks:
    - name: Update apt packages
      raw: sudo apt-get update
      tags: ['ubuntu']

    - name: Install python & aptitude for ansible
      raw: sudo apt install python aptitude -y
      tags: ['ubuntu']
      
    - name: install ntp
      raw: sudo apt install ntp -y
      tags: ['ubuntu']
      
    - name: install ntp Update
      raw: sudo apt install ntpdate -y
      tags: ['ubuntu']

    - name: install clam av
      raw: sudo apt install clamav -y  
      tags: ['ubuntu']
    

